export type ThemeConfig = {
  id: string;
  name: string;
  description: string;
  previewColor: string;
  roomBg: string;
  panelBg: string;
  borderColor: string;
  accentText: string;
  buttonBg: string;
  buttonHover: string;
  particleType?: 'hearts' | 'fire' | 'snow' | 'stars' | 'cherry' | 'grid' | 'confetti' | 'fog';
  ambientGlow?: string;
  extraStyles?: string;
};

export const THEMES: Record<string, ThemeConfig> = {
  minimal: {
    id: "minimal",
    name: "Minimal",
    description: "Maximum focus on the movie",
    previewColor: "bg-burgundy-950",
    roomBg: "bg-burgundy-950",
    panelBg: "bg-burgundy-950/60",
    borderColor: "border-burgundy-900/50",
    accentText: "text-maroon-500",
    buttonBg: "bg-maroon-700",
    buttonHover: "hover:bg-maroon-600",
  },
  romantic: {
    id: "romantic",
    name: "Romantic",
    description: "Soft pinks and rose petals",
    previewColor: "bg-pink-900",
    roomBg: "bg-[#2d0f1b]",
    panelBg: "bg-pink-950/40",
    borderColor: "border-pink-900/50",
    accentText: "text-pink-400",
    buttonBg: "bg-pink-600",
    buttonHover: "hover:bg-pink-500",
    particleType: "hearts",
    ambientGlow: "shadow-[0_0_50px_rgba(255,100,150,0.15)]",
  },
  family: {
    id: "family",
    name: "Family",
    description: "Cozy and warm atmosphere",
    previewColor: "bg-orange-900",
    roomBg: "bg-[#26150a]",
    panelBg: "bg-orange-950/40",
    borderColor: "border-orange-900/50",
    accentText: "text-orange-400",
    buttonBg: "bg-orange-600",
    buttonHover: "hover:bg-orange-500",
    ambientGlow: "shadow-[0_0_50px_rgba(255,150,50,0.1)]",
  },
  mass: {
    id: "mass",
    name: "Mass",
    description: "Epic cinematic fire and embers",
    previewColor: "bg-red-950",
    roomBg: "bg-[#1a0505]",
    panelBg: "bg-red-950/40",
    borderColor: "border-red-900/50",
    accentText: "text-red-500",
    buttonBg: "bg-red-700",
    buttonHover: "hover:bg-red-600",
    particleType: "fire",
  },
  horror: {
    id: "horror",
    name: "Horror",
    description: "Dark, fog, and green mist",
    previewColor: "bg-green-950",
    roomBg: "bg-[#05100a]",
    panelBg: "bg-green-950/20",
    borderColor: "border-green-900/30",
    accentText: "text-green-500",
    buttonBg: "bg-green-800",
    buttonHover: "hover:bg-green-700",
    particleType: "fog",
  },
  scifi: {
    id: "scifi",
    name: "Sci-Fi",
    description: "Cyberpunk blue and neon grid",
    previewColor: "bg-blue-900",
    roomBg: "bg-[#050a1f]",
    panelBg: "bg-blue-950/40",
    borderColor: "border-blue-800/50",
    accentText: "text-cyan-400",
    buttonBg: "bg-blue-600",
    buttonHover: "hover:bg-blue-500",
    particleType: "grid",
    ambientGlow: "shadow-[0_0_50px_rgba(0,100,255,0.2)]",
  },
  fantasy: {
    id: "fantasy",
    name: "Fantasy",
    description: "Magical sparkles and purple sky",
    previewColor: "bg-purple-900",
    roomBg: "bg-[#150524]",
    panelBg: "bg-purple-950/40",
    borderColor: "border-purple-800/50",
    accentText: "text-purple-400",
    buttonBg: "bg-purple-600",
    buttonHover: "hover:bg-purple-500",
    particleType: "stars",
  },
  anime: {
    id: "anime",
    name: "Anime",
    description: "Cherry blossoms and pastel glow",
    previewColor: "bg-fuchsia-900",
    roomBg: "bg-[#240a1b]",
    panelBg: "bg-fuchsia-950/40",
    borderColor: "border-fuchsia-800/50",
    accentText: "text-pink-300",
    buttonBg: "bg-fuchsia-600",
    buttonHover: "hover:bg-fuchsia-500",
    particleType: "cherry",
  },
  retro: {
    id: "retro",
    name: "Retro",
    description: "80s synthwave glow",
    previewColor: "bg-indigo-900",
    roomBg: "bg-[#11051f]",
    panelBg: "bg-indigo-950/40",
    borderColor: "border-indigo-800/50",
    accentText: "text-pink-500",
    buttonBg: "bg-indigo-600",
    buttonHover: "hover:bg-indigo-500",
    particleType: "grid",
    ambientGlow: "shadow-[0_0_60px_rgba(200,0,255,0.15)]",
  },
  festival: {
    id: "festival",
    name: "Festival",
    description: "Colorful confetti party",
    previewColor: "bg-yellow-900",
    roomBg: "bg-[#1a1405]",
    panelBg: "bg-yellow-950/40",
    borderColor: "border-yellow-900/50",
    accentText: "text-yellow-400",
    buttonBg: "bg-yellow-600",
    buttonHover: "hover:bg-yellow-500",
    particleType: "confetti",
  },
  cinemaGold: {
    id: "cinemaGold",
    name: "Cinema Gold",
    description: "Luxury black and premium gold",
    previewColor: "bg-amber-700",
    roomBg: "bg-[#0a0a0a]",
    panelBg: "bg-yellow-900/10",
    borderColor: "border-yellow-600/30",
    accentText: "text-yellow-500",
    buttonBg: "bg-yellow-700",
    buttonHover: "hover:bg-yellow-600",
    ambientGlow: "shadow-[0_0_80px_rgba(255,200,0,0.08)]",
  }
};
